version: '3'

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=ASDFqwer1234
  api:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db