# Generated by Django 2.1.7 on 2019-04-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='dark_image',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='light_image',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
    ]
